import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { Brain, FileText, Calendar, AlertCircle } from "lucide-react";
import { Spinner, Alert } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { aiApi } from "../../services/ai";
import { getErrorMessage } from "../../services/api";

export default function PatientAISummary() {
  const { publicId } = useParams();
  const decoded = decodeURIComponent(publicId);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const response = await aiApi.getPatientSummary(decoded);
        if (!cancelled) {
          setSummary(response.data.data);
        }
      } catch (err) {
        if (!cancelled) setError(getErrorMessage(err, "No AI summary available for this patient."));
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [decoded]);

  if (loading) {
    return (
      <div className="flex justify-center py-20">
        <Spinner className="h-7 w-7" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-2xl">
        <div className="mb-6">
          <h1 className="font-display text-2xl">AI Patient Summary</h1>
          <p className="text-muted">AI-generated summary from patient interactions</p>
        </div>
        <Alert className="flex items-start gap-3">
          <AlertCircle className="h-5 w-5 mt-0.5" />
          <div>
            <p className="font-medium">No Summary Available</p>
            <p className="text-sm mt-1">{error}</p>
          </div>
        </Alert>
      </div>
    );
  }

  return (
    <div className="max-w-4xl">
      <div className="mb-6">
        <h1 className="font-display text-2xl">AI Patient Summary</h1>
        <p className="text-muted">AI-generated summary from patient interactions with Meddy</p>
      </div>

      <div className="bg-white rounded-2xl border border-line shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-line bg-gray-50">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-teal-100 rounded-lg">
                <Brain className="h-5 w-5 text-teal-700" />
              </div>
              <div>
                <h3 className="font-medium">AI-Generated Summary</h3>
                <p className="text-sm text-muted">
                  Generated on {new Date(summary.date).toLocaleString()}
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2 text-xs text-muted">
              <Calendar className="h-4 w-4" />
              <span>Latest</span>
            </div>
          </div>
        </div>

        <div className="p-6">
          <div className="prose prose-sm max-w-none">
            <div className="whitespace-pre-wrap text-gray-700 leading-relaxed">
              {summary.summary}
            </div>
          </div>
        </div>

        <div className="px-6 py-4 border-t border-line bg-gray-50">
          <div className="flex items-center gap-2 text-xs text-muted">
            <FileText className="h-4 w-4" />
            <span>
              This summary was generated by AI based on patient's chat history. 
              Always verify with the patient during consultation.
            </span>
          </div>
        </div>
      </div>

      <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <div className="flex items-start gap-3">
          <AlertCircle className="h-5 w-5 text-blue-600 mt-0.5" />
          <div>
            <p className="font-medium text-blue-900">Clinical Note</p>
            <p className="text-sm text-blue-700 mt-1">
              This AI summary provides context from the patient's self-reported symptoms and interactions. 
              Use this as a reference point during your examination, but always conduct your own assessment 
              and verify information directly with the patient.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
