"""add assign roles

Revision ID: 8e758cc4d501
Revises: f536ae101eb2
Create Date: 2026-08-21 15:05:14.837493

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '8e758cc4d501'
down_revision = 'f536ae101eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', app.utils.db_types.GUID(), nullable=False))
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_foreign_key(None, 'ai_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
