"""new tables

Revision ID: 932b24c1a133
Revises: 
Create Date: 2026-08-21 08:16:14.414671

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '932b24c1a133'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('reg_no', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_hospitals_reg_no'), ['reg_no'], unique=True)

    op.create_table('patients',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('public_id', sa.String(length=12), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('nin', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("sex IN ('Male', 'Female')", name='valid_sex_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nin')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_public_id'), ['public_id'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('actor_roles',
    sa.Column('actor_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'actor_type', 'role_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('staff',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('hospital_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('nin', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("sex IN ('Male', 'Female')", name='valid_sex_status'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nin'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=True)

    op.create_table('access_requests',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('patient_public_id', sa.String(length=12), nullable=False),
    sa.Column('staff_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('hospital_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('Pending', 'Approved', 'Denied')", name='valid_request_status'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_public_id'], ['patients.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_requests_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_patient_public_id'), ['patient_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_staff_id'), ['staff_id'], unique=False)

    op.create_table('medical_records',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('hospital_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('doctor_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('patient_public_id', sa.String(length=12), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_public_id'], ['patients.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_patient_public_id'), ['patient_public_id'], unique=False)

    op.create_table('access_grants',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('request_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('patient_public_id', sa.String(length=12), nullable=False),
    sa.Column('staff_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('hospital_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('Granted', 'Revoked', 'Expired')", name='valid_grant_status'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_public_id'], ['patients.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['access_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_grants_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_patient_public_id'), ['patient_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_staff_id'), ['staff_id'], unique=False)

    op.create_table('record_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('record_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_documents_record_id'), ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_documents_record_id'))

    op.drop_table('record_documents')
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_grants_staff_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_patient_public_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_hospital_id'))

    op.drop_table('access_grants')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_patient_public_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_doctor_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_requests_staff_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_patient_public_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_hospital_id'))

    op.drop_table('access_requests')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_email'))

    op.drop_table('staff')
    op.drop_table('role_permissions')
    op.drop_table('actor_roles')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('roles')
    op.drop_table('permissions')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_public_id'))
        batch_op.drop_index(batch_op.f('ix_patients_phone'))

    op.drop_table('patients')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_reg_no'))
        batch_op.drop_index(batch_op.f('ix_hospitals_email'))

    op.drop_table('hospitals')
    # ### end Alembic commands ###
