"""added ai

Revision ID: f536ae101eb2
Revises: 932b24c1a133
Create Date: 2026-08-21 12:44:14.447659

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = 'f536ae101eb2'
down_revision = '932b24c1a133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('patient_public_id', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symptom_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_public_id'], ['patients.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_patient_public_id'), ['patient_public_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('patient_public_id', sa.String(length=12), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_public_id'], ['patients.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_patient_public_id'), ['patient_public_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', app.utils.db_types.GUID(), nullable=False),
    sa.Column('patient_public_id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_public_id'], ['patients.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_patient_public_id'), ['patient_public_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('genotype', sa.String(length=5), nullable=True))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('record_documents', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_staff_specialty'), ['specialty'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_specialty'))
        batch_op.drop_column('specialty')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('record_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('genotype')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('allergies')

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_patient_public_id'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_created_at'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_patient_public_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_patient_public_id'))

    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
